version: "2"

volumes:
  postgres-data:

services:
  # postgres:
  #   image: kartoza/postgis:12.1
  #   restart: "no"
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=gis
  #     - POSTGRES_PASS=peder
  #     - POSTGRES_DBNAME=gis
  #     - ALLOW_IP_RANGE=0.0.0.0/0
  #     - IP_LIST=*
  #   volumes:
  #     - postgres-data:/var/lib/postgresql

  postgres:
    image: postgis/postgis
    ports:
      - 5432:5432
    environment:
    # User = postgres
      - POSTGRES_PASSWORD=peder
    volumes:
      - postgres-data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - 80:80

# docker run -p 80:80 \
#     -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' \
#     -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
#     -d dpage/pgadmin4